// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKSAOGOQJ5L_hwXkfs23uwx2xWVAgOkAA',
    appId: '1:1077854815287:web:018033f0e4b8507a0b6bb2',
    messagingSenderId: '1077854815287',
    projectId: 'login-page-a0bd0',
    authDomain: 'login-page-a0bd0.firebaseapp.com',
    storageBucket: 'login-page-a0bd0.appspot.com',
    measurementId: 'G-2YEFQ8R78P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFoTfNqyFkOLQbokBtMiadjryBfNeDcuo',
    appId: '1:1077854815287:android:aca4e04d8d6e60090b6bb2',
    messagingSenderId: '1077854815287',
    projectId: 'login-page-a0bd0',
    storageBucket: 'login-page-a0bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1nTGSX9gSwBpQlNkmu0RPdT414XEPaU',
    appId: '1:1077854815287:ios:e17c83b00ba869330b6bb2',
    messagingSenderId: '1077854815287',
    projectId: 'login-page-a0bd0',
    storageBucket: 'login-page-a0bd0.appspot.com',
    iosBundleId: 'com.example.flutterLoginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU1nTGSX9gSwBpQlNkmu0RPdT414XEPaU',
    appId: '1:1077854815287:ios:dc85390bab8adbab0b6bb2',
    messagingSenderId: '1077854815287',
    projectId: 'login-page-a0bd0',
    storageBucket: 'login-page-a0bd0.appspot.com',
    iosBundleId: 'com.example.flutterLoginPage.RunnerTests',
  );
}
